class Fnd < Formula
  include Language::Python::Virtualenv

  desc "Fast, free, keyboard-driven document search for macOS"
  homepage "https://github.com/ben-dev-au/fnd"
  # url + sha256 are overwritten by the release workflow's bump job on
  # each `v*` tag (resolved from PyPI's JSON for the `fndr` dist).
  url "https://files.pythonhosted.org/packages/source/f/fndr/fndr-0.0.1.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"

  depends_on "python@3.13"

  # `resource` blocks are generated by `brew update-python-resources fnd`
  # after the first publish lands on PyPI. The release workflow's
  # `bump-homebrew-tap` job opens a PR that bumps `url` + `sha256`; a
  # follow-up run of `brew update-python-resources` (manual or via
  # `dawidd6/action-homebrew-bump-formula`) refreshes resource blocks
  # if any transitive pin changed.

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fnd version")
  end
end
